vars:
  - params.yaml

stages:
  preprocess_load_dataset:
    cmd: python src/load_data.py --url ${preprocess.load_data.url} --dst ${general.dataset} --per ${preprocess.load_data.per} --ann ${general.ann_train} ${general.ann_val}
    deps:
      - src/load_data.py
    outs:
      - ${general.dataset}
      
    
  preprocess_analysis_data:
    cmd: python src/analysis_data.py --src ${general.dataset} --dst ${preprocess.analysis_data.dst} --ann ${general.ann_train} ${general.ann_val}
    dep:
      - ${general.dataset}
      - src/analysis_data.py
    outs:
      - ${preprocess.analysis_data.dst}
    
  preprocess_convert_data:
    cmd: python src/prepare_data.py --src ${general.dataset} --dst ${general.prepared} --yml ${preprocess.convert_data.yml} --ann ${general.ann_train} ${general.ann_val}
    dep:
      - ${general.dataset}
      - src/prepare_data.py
    outs:
      - ${general.prepared}

  train:
    cmd: python src/train.py --data ${preprocess.convert_data.yml} --wght ${train.version} --gpu --opt ${train.regul.optim} --epo ${train.other.epo} --bsz ${train.other.bsize} --isz ${train.other.imsz} --lr0 {train.regul.lr0}
    dep:
      - ${general.prepared}
      - ${preprocess.convert_data.yml}
      - src/train.py
    outs:
      -outs